Comp 147/fallback language
micro-lc/micro-lc pull request #924
Opened 2024-03-19 13:29 UTC by FabioNappi

## Pull Request Type

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Description

Added `fallback-language` property in micro-lc web component

## PR Checklist

- [x] The commit message follows our guidelines included in the [CONTRIBUTING.md](../CONTRIBUTING.md#how-to-submit-a-pr)
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Relevant CHANGELOG (`packages/<package>/CHANGELOG.md`) is updated
- [x]  Documentation was updated or a PR to the [docs](https://github.com/micro-lc/micro-lc.github.io/pulls) is on its way (link it pls)

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2024-03-19 19:08 UTC, amountainram requested changes

2024-03-19 19:08 UTC, amountainram commented on CHANGELOG.md
> +### Added
Pls, do not update this `CHANGELOG.md` since it is automatically generated.
These lines belong to packages/orchestrator/CHANGELOG.md

2024-03-19 19:08 UTC, amountainram commented on tests/config.spec.ts
> +  // SAFETY: verified locally on firefox and epiphany
would you mind reporting it like:

```
// SAFETY: Playwright API testing does not work fine with firefox and webkit/epiphany due to fuzzy interplay with service workers
```

2024-03-20 08:16 UTC, FabioNappi commented
> @FabioNappi Can you also add a documentation remark at https://github.com/micro-lc/micro-lc.github.io/blob/main/docs/api/micro-lc-web-component.md?

here it is https://github.com/micro-lc/micro-lc.github.io/pull/476

2024-03-20 09:59 UTC, amountainram approved these changes

2024-03-20 09:59 UTC, merged